DROP TABLE IF EXISTS inv;

CREATE TABLE inv (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    suz TEXT NOT NULL,
    client TEXT NOT NULL,
    service INTEGER NOT NULL,
    pe TEXT NOT NULL,
    pe_if TEXT NOT NULL,
    vid INTEGER NOT NULL
);
